// <auto-generated />
namespace coffeeSalesManag_CompApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomerTableUpdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomerTableUpdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201703210357294_CustomerTableUpdated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
